# Generated by Django 6.0.7 on 2026-07-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0005_add_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weightentry',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Notes'),
        ),
    ]
