sonar.projectKey=cmn07_wger
sonar.organization=cmn07


sonar.sources=wger
sonar.python.version=3.12
sonar.exclusions=**/migrations/**,**/static/**,**/node_modules/**,**/__pycache__/**
sonar.sourceEncoding=UTF-8
