sonar.projectKey=${SONAR_PROJECT_KEY}
sonar.organization=${SONAR_ORGANIZATION}
sonar.projectName=wger
sonar.sources=wger
sonar.sourceEncoding=UTF-8
sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**,**/migrations/**
