# Generated by Django 6.0.7 on 2026-07-14 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercises', '0040_alter_exercise_license_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltranslation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicaltranslation',
            name='description_source',
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(40)],
                verbose_name='Description (Source)',
            ),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='description_source',
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(40)],
                verbose_name='Description (Source)',
            ),
        ),
    ]
